<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-8BGFE0TE" ignored="0" name="TC007_LoginTest" tests="3" failures="1" timestamp="18 May 2021 18:35:04 GMT" time="37.949" errors="0">
  <testcase name="loginTest" time="6.286" classname="ParallelExecution.TC007_LoginTest"/>
  <testcase name="pageTitleTest" time="0.158" classname="ParallelExecution.TC007_LoginTest">
    <failure type="java.lang.AssertionError" message="expected [Login in to your account] but found [Log in to your account]">
      <![CDATA[java.lang.AssertionError: expected [Login in to your account] but found [Log in to your account]
at ParallelExecution.TC007_LoginTest.pageTitleTest(TC007_LoginTest.java:56)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- pageTitleTest -->
  <testcase name="signupLinkTest" time="0.555" classname="ParallelExecution.TC007_LoginTest"/>
</testsuite> <!-- TC007_LoginTest -->
